export const expectedStringsData = {
  0: {
    rootNote: "g2",
    frets: {
      0: {
        noteName: "g",
        octave: "2",
        interval: "P1",
        markerEnabled: true,
        ref: { current: null },
      },
      1: {
        noteName: "ab",
        octave: "2",
        interval: "m2",
        markerEnabled: true,
        ref: { current: null },
      },
      2: {
        noteName: "a",
        octave: "2",
        interval: "M2",
        markerEnabled: true,
        ref: { current: null },
      },
      3: {
        noteName: "bb",
        octave: "2",
        interval: "m3",
        markerEnabled: true,
        ref: { current: null },
      },
      4: {
        noteName: "b",
        octave: "2",
        interval: "M3",
        markerEnabled: true,
        ref: { current: null },
      },
      5: {
        noteName: "c",
        octave: "3",
        interval: "P4",
        markerEnabled: true,
        ref: { current: null },
      },
      6: {
        noteName: "db",
        octave: "3",
        interval: "d5",
        markerEnabled: true,
        ref: { current: null },
      },
    },
  },
  1: {
    rootNote: "d3",
    frets: {
      0: {
        noteName: "d",
        octave: "3",
        interval: "P1",
        markerEnabled: true,
        ref: { current: null },
      },
      1: {
        noteName: "eb",
        octave: "3",
        interval: "m2",
        markerEnabled: true,
        ref: { current: null },
      },
      2: {
        noteName: "e",
        octave: "3",
        interval: "M2",
        markerEnabled: true,
        ref: { current: null },
      },
      3: {
        noteName: "f",
        octave: "3",
        interval: "m3",
        markerEnabled: true,
        ref: { current: null },
      },
      4: {
        noteName: "f#",
        octave: "3",
        interval: "M3",
        markerEnabled: true,
        ref: { current: null },
      },
      5: {
        noteName: "g",
        octave: "3",
        interval: "P4",
        markerEnabled: true,
        ref: { current: null },
      },
      6: {
        noteName: "ab",
        octave: "3",
        interval: "d5",
        markerEnabled: true,
        ref: { current: null },
      },
    },
  },
  2: {
    rootNote: "a3",
    frets: {
      0: {
        noteName: "a",
        octave: "3",
        interval: "P1",
        markerEnabled: true,
        ref: { current: null },
      },
      1: {
        noteName: "bb",
        octave: "3",
        interval: "m2",
        markerEnabled: true,
        ref: { current: null },
      },
      2: {
        noteName: "b",
        octave: "3",
        interval: "M2",
        markerEnabled: true,
        ref: { current: null },
      },
      3: {
        noteName: "c",
        octave: "4",
        interval: "m3",
        markerEnabled: true,
        ref: { current: null },
      },
      4: {
        noteName: "c#",
        octave: "4",
        interval: "M3",
        markerEnabled: true,
        ref: { current: null },
      },
      5: {
        noteName: "d",
        octave: "4",
        interval: "P4",
        markerEnabled: true,
        ref: { current: null },
      },
      6: {
        noteName: "eb",
        octave: "4",
        interval: "d5",
        markerEnabled: true,
        ref: { current: null },
      },
    },
  },
  3: {
    rootNote: "e4",
    frets: {
      0: {
        noteName: "e",
        octave: "4",
        interval: "P1",
        markerEnabled: true,
        ref: { current: null },
      },
      1: {
        noteName: "f",
        octave: "4",
        interval: "m2",
        markerEnabled: true,
        ref: { current: null },
      },
      2: {
        noteName: "f#",
        octave: "4",
        interval: "M2",
        markerEnabled: true,
        ref: { current: null },
      },
      3: {
        noteName: "g",
        octave: "4",
        interval: "m3",
        markerEnabled: true,
        ref: { current: null },
      },
      4: {
        noteName: "g#",
        octave: "4",
        interval: "M3",
        markerEnabled: true,
        ref: { current: null },
      },
      5: {
        noteName: "a",
        octave: "4",
        interval: "P4",
        markerEnabled: true,
        ref: { current: null },
      },
      6: {
        noteName: "bb",
        octave: "4",
        interval: "d5",
        markerEnabled: true,
        ref: { current: null },
      },
    },
  },
};
